package set3r.kmv.ca.helpmenewwest.database.schema;

import android.location.Location;

import com.google.android.gms.maps.model.LatLng;

import org.greenrobot.greendao.annotation.*;

import set3r.kmv.ca.helpmenewwest.CompareDistance;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ALTERNATIVE_FUEL".
 */
@Entity
<<<<<<< HEAD:app/src/main/java/set3r/kmv/ca/helpmenewwest/database/schema/AlternateFuel.java
public class AlternateFuel implements CompareDistance{
=======
public class AlternativeFuel {
>>>>>>> b9b3e32e176c06f63e4b74e6148c7a5aefe225fb:app/src/main/java/set3r/kmv/ca/helpmenewwest/database/schema/AlternativeFuel.java

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;

    @NotNull
    private String address;
    private String description;
    private double lat;
    private double lng;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public AlternativeFuel() {
    }

    public AlternativeFuel(Long id) {
        this.id = id;
    }

    @Generated
    public AlternativeFuel(Long id, String name, String address, String description, double lat, double lng) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.description = description;
        this.lat = lat;
        this.lng = lng;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(@NotNull String address) {
        this.address = address;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    // KEEP METHODS - put your custom methods here

    public String toString(){
        return getName();
    }

    public LatLng getLatLng() {
        return new LatLng(this.getLat(), this.getLng());
    }

    public Location getLocation() {
        Location temp = new Location(this.getName());
        temp.setLatitude(this.getLat());
        temp.setLongitude(this.getLng());
        return temp;
    }
    // KEEP METHODS END

}
