package set3r.kmv.ca.helpmenewwest.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import set3r.kmv.ca.helpmenewwest.database.schema.Fire;
import set3r.kmv.ca.helpmenewwest.database.schema.Police;
import set3r.kmv.ca.helpmenewwest.database.schema.Park;
import set3r.kmv.ca.helpmenewwest.database.schema.Hospital;
import set3r.kmv.ca.helpmenewwest.database.schema.AlternateFuel;
import set3r.kmv.ca.helpmenewwest.database.schema.BusStop;
import set3r.kmv.ca.helpmenewwest.database.schema.Skytrain;

import set3r.kmv.ca.helpmenewwest.database.schema.FireDao;
import set3r.kmv.ca.helpmenewwest.database.schema.PoliceDao;
import set3r.kmv.ca.helpmenewwest.database.schema.ParkDao;
import set3r.kmv.ca.helpmenewwest.database.schema.HospitalDao;
import set3r.kmv.ca.helpmenewwest.database.schema.AlternateFuelDao;
import set3r.kmv.ca.helpmenewwest.database.schema.BusStopDao;
import set3r.kmv.ca.helpmenewwest.database.schema.SkytrainDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fireDaoConfig;
    private final DaoConfig policeDaoConfig;
    private final DaoConfig parkDaoConfig;
    private final DaoConfig hospitalDaoConfig;
    private final DaoConfig alternateFuelDaoConfig;
    private final DaoConfig busStopDaoConfig;
    private final DaoConfig skytrainDaoConfig;

    private final FireDao fireDao;
    private final PoliceDao policeDao;
    private final ParkDao parkDao;
    private final HospitalDao hospitalDao;
    private final AlternateFuelDao alternateFuelDao;
    private final BusStopDao busStopDao;
    private final SkytrainDao skytrainDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fireDaoConfig = daoConfigMap.get(FireDao.class).clone();
        fireDaoConfig.initIdentityScope(type);

        policeDaoConfig = daoConfigMap.get(PoliceDao.class).clone();
        policeDaoConfig.initIdentityScope(type);

        parkDaoConfig = daoConfigMap.get(ParkDao.class).clone();
        parkDaoConfig.initIdentityScope(type);

        hospitalDaoConfig = daoConfigMap.get(HospitalDao.class).clone();
        hospitalDaoConfig.initIdentityScope(type);

        alternateFuelDaoConfig = daoConfigMap.get(AlternateFuelDao.class).clone();
        alternateFuelDaoConfig.initIdentityScope(type);

        busStopDaoConfig = daoConfigMap.get(BusStopDao.class).clone();
        busStopDaoConfig.initIdentityScope(type);

        skytrainDaoConfig = daoConfigMap.get(SkytrainDao.class).clone();
        skytrainDaoConfig.initIdentityScope(type);

        fireDao = new FireDao(fireDaoConfig, this);
        policeDao = new PoliceDao(policeDaoConfig, this);
        parkDao = new ParkDao(parkDaoConfig, this);
        hospitalDao = new HospitalDao(hospitalDaoConfig, this);
        alternateFuelDao = new AlternateFuelDao(alternateFuelDaoConfig, this);
        busStopDao = new BusStopDao(busStopDaoConfig, this);
        skytrainDao = new SkytrainDao(skytrainDaoConfig, this);

        registerDao(Fire.class, fireDao);
        registerDao(Police.class, policeDao);
        registerDao(Park.class, parkDao);
        registerDao(Hospital.class, hospitalDao);
        registerDao(AlternateFuel.class, alternateFuelDao);
        registerDao(BusStop.class, busStopDao);
        registerDao(Skytrain.class, skytrainDao);
    }
    
    public void clear() {
        fireDaoConfig.clearIdentityScope();
        policeDaoConfig.clearIdentityScope();
        parkDaoConfig.clearIdentityScope();
        hospitalDaoConfig.clearIdentityScope();
        alternateFuelDaoConfig.clearIdentityScope();
        busStopDaoConfig.clearIdentityScope();
        skytrainDaoConfig.clearIdentityScope();
    }

    public FireDao getFireDao() {
        return fireDao;
    }

    public PoliceDao getPoliceDao() {
        return policeDao;
    }

    public ParkDao getParkDao() {
        return parkDao;
    }

    public HospitalDao getHospitalDao() {
        return hospitalDao;
    }

    public AlternateFuelDao getAlternateFuelDao() {
        return alternateFuelDao;
    }

    public BusStopDao getBusStopDao() {
        return busStopDao;
    }

    public SkytrainDao getSkytrainDao() {
        return skytrainDao;
    }

}
