package set3r.kmv.ca.helpmenewwest.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import set3r.kmv.ca.helpmenewwest.database.schema.Community;
import set3r.kmv.ca.helpmenewwest.database.schema.Fire;
import set3r.kmv.ca.helpmenewwest.database.schema.Police;
import set3r.kmv.ca.helpmenewwest.database.schema.Park;
import set3r.kmv.ca.helpmenewwest.database.schema.Hospital;

import set3r.kmv.ca.helpmenewwest.database.schema.CommunityDao;
import set3r.kmv.ca.helpmenewwest.database.schema.FireDao;
import set3r.kmv.ca.helpmenewwest.database.schema.PoliceDao;
import set3r.kmv.ca.helpmenewwest.database.schema.ParkDao;
import set3r.kmv.ca.helpmenewwest.database.schema.HospitalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig communityDaoConfig;
    private final DaoConfig fireDaoConfig;
    private final DaoConfig policeDaoConfig;
    private final DaoConfig parkDaoConfig;
    private final DaoConfig hospitalDaoConfig;

    private final CommunityDao communityDao;
    private final FireDao fireDao;
    private final PoliceDao policeDao;
    private final ParkDao parkDao;
    private final HospitalDao hospitalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        communityDaoConfig = daoConfigMap.get(CommunityDao.class).clone();
        communityDaoConfig.initIdentityScope(type);

        fireDaoConfig = daoConfigMap.get(FireDao.class).clone();
        fireDaoConfig.initIdentityScope(type);

        policeDaoConfig = daoConfigMap.get(PoliceDao.class).clone();
        policeDaoConfig.initIdentityScope(type);

        parkDaoConfig = daoConfigMap.get(ParkDao.class).clone();
        parkDaoConfig.initIdentityScope(type);

        hospitalDaoConfig = daoConfigMap.get(HospitalDao.class).clone();
        hospitalDaoConfig.initIdentityScope(type);

        communityDao = new CommunityDao(communityDaoConfig, this);
        fireDao = new FireDao(fireDaoConfig, this);
        policeDao = new PoliceDao(policeDaoConfig, this);
        parkDao = new ParkDao(parkDaoConfig, this);
        hospitalDao = new HospitalDao(hospitalDaoConfig, this);

        registerDao(Community.class, communityDao);
        registerDao(Fire.class, fireDao);
        registerDao(Police.class, policeDao);
        registerDao(Park.class, parkDao);
        registerDao(Hospital.class, hospitalDao);
    }
    
    public void clear() {
        communityDaoConfig.clearIdentityScope();
        fireDaoConfig.clearIdentityScope();
        policeDaoConfig.clearIdentityScope();
        parkDaoConfig.clearIdentityScope();
        hospitalDaoConfig.clearIdentityScope();
    }

    public CommunityDao getCommunityDao() {
        return communityDao;
    }

    public FireDao getFireDao() {
        return fireDao;
    }

    public PoliceDao getPoliceDao() {
        return policeDao;
    }

    public ParkDao getParkDao() {
        return parkDao;
    }

    public HospitalDao getHospitalDao() {
        return hospitalDao;
    }

}
