package set3r.kmv.ca.helpmenewwest.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import set3r.kmv.ca.helpmenewwest.database.schema.community_services;
import set3r.kmv.ca.helpmenewwest.database.schema.fire_stations;
import set3r.kmv.ca.helpmenewwest.database.schema.police_stations;
import set3r.kmv.ca.helpmenewwest.database.schema.parks;
import set3r.kmv.ca.helpmenewwest.database.schema.hospitals;

import set3r.kmv.ca.helpmenewwest.database.schema.community_servicesDao;
import set3r.kmv.ca.helpmenewwest.database.schema.fire_stationsDao;
import set3r.kmv.ca.helpmenewwest.database.schema.police_stationsDao;
import set3r.kmv.ca.helpmenewwest.database.schema.parksDao;
import set3r.kmv.ca.helpmenewwest.database.schema.hospitalsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig community_servicesDaoConfig;
    private final DaoConfig fire_stationsDaoConfig;
    private final DaoConfig police_stationsDaoConfig;
    private final DaoConfig parksDaoConfig;
    private final DaoConfig hospitalsDaoConfig;

    private final community_servicesDao community_servicesDao;
    private final fire_stationsDao fire_stationsDao;
    private final police_stationsDao police_stationsDao;
    private final parksDao parksDao;
    private final hospitalsDao hospitalsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        community_servicesDaoConfig = daoConfigMap.get(community_servicesDao.class).clone();
        community_servicesDaoConfig.initIdentityScope(type);

        fire_stationsDaoConfig = daoConfigMap.get(fire_stationsDao.class).clone();
        fire_stationsDaoConfig.initIdentityScope(type);

        police_stationsDaoConfig = daoConfigMap.get(police_stationsDao.class).clone();
        police_stationsDaoConfig.initIdentityScope(type);

        parksDaoConfig = daoConfigMap.get(parksDao.class).clone();
        parksDaoConfig.initIdentityScope(type);

        hospitalsDaoConfig = daoConfigMap.get(hospitalsDao.class).clone();
        hospitalsDaoConfig.initIdentityScope(type);

        community_servicesDao = new community_servicesDao(community_servicesDaoConfig, this);
        fire_stationsDao = new fire_stationsDao(fire_stationsDaoConfig, this);
        police_stationsDao = new police_stationsDao(police_stationsDaoConfig, this);
        parksDao = new parksDao(parksDaoConfig, this);
        hospitalsDao = new hospitalsDao(hospitalsDaoConfig, this);

        registerDao(community_services.class, community_servicesDao);
        registerDao(fire_stations.class, fire_stationsDao);
        registerDao(police_stations.class, police_stationsDao);
        registerDao(parks.class, parksDao);
        registerDao(hospitals.class, hospitalsDao);
    }
    
    public void clear() {
        community_servicesDaoConfig.clearIdentityScope();
        fire_stationsDaoConfig.clearIdentityScope();
        police_stationsDaoConfig.clearIdentityScope();
        parksDaoConfig.clearIdentityScope();
        hospitalsDaoConfig.clearIdentityScope();
    }

    public community_servicesDao getCommunity_servicesDao() {
        return community_servicesDao;
    }

    public fire_stationsDao getFire_stationsDao() {
        return fire_stationsDao;
    }

    public police_stationsDao getPolice_stationsDao() {
        return police_stationsDao;
    }

    public parksDao getParksDao() {
        return parksDao;
    }

    public hospitalsDao getHospitalsDao() {
        return hospitalsDao;
    }

}
