package set3r.kmv.ca.helpmenewwest.database.schema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PARK".
 */
@Entity
public class Park {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;

    @NotNull
    private String category_id;

    @NotNull
    private String street_num;

    @NotNull
    private String street_name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Park() {
    }

    public Park(Long id) {
        this.id = id;
    }

    @Generated
    public Park(Long id, String name, String category_id, String street_num, String street_name) {
        this.id = id;
        this.name = name;
        this.category_id = category_id;
        this.street_num = street_num;
        this.street_name = street_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getCategory_id() {
        return category_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_id(@NotNull String category_id) {
        this.category_id = category_id;
    }

    @NotNull
    public String getStreet_num() {
        return street_num;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStreet_num(@NotNull String street_num) {
        this.street_num = street_num;
    }

    @NotNull
    public String getStreet_name() {
        return street_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStreet_name(@NotNull String street_name) {
        this.street_name = street_name;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getName();
    }
    // KEEP METHODS END

}
